### ISSUE TITLE
Keys instead of values

### ISSUE THREAD

**Issue by veryrare-software** [LeoClose/godot-firebase-lite#2]
Hello, I'm  trying to write a dictionary to Firestore, but it replaces values with keys.

Code:
```
var res = await FirebaseLite.Firestore.write(COLLECTION_ID + scoreDict["level"]+"/"+scoreDict["userName"], scoreDict)
print("saveScore to firebase result: ")
print(res)
```

Results: `{ "level": "level", "timestamp": "timestamp", "trickScore": "trickScore" ... }`

Expected Result:  actual values

Any idea what can cause it?

For now, I use workaround like this, just wrapping it in another dictionary 
```
saving score: { "fields": { "bestEntryTime": 1243, "timestamp": 1234, "noRollback": false, "trickScore": 123, "userName": "DFFG", "level": "4" } }
```

**Comment by LeoClose** [comment]
I apologize for the late reply, I was inactive for some time to focus on some things.

Your problem was due to a typo in the processDictionary function which I just fixed.

**Comment by LeoClose** [comment]
I apologize for the late reply and any inconvenience caused, I was inactive for some time to focus on some things.

Your problem was due to a typo in the processDictionary function which I just fixed.
